Script started on Wed 04 Sep 2019 07:53:49 PM CDT
[?1034hbash-4.2$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC) 
bash-4.2$ gcc -g -lm -o simple simple.c
bash-4.2$ man ldd
[?1049h[?1h=LDD(1)                     Linux Programmer's Manual                    LDD(1)[m
[m
[1mNAME[0m[m
       ldd - print shared library dependencies[m
[m
[1mSYNOPSIS[0m[m
       [1mldd[0m [OPTION]... FILE...[m
[m
[1mDESCRIPTION[0m[m
       [1mldd[0m  prints  the  shared  libraries  required by each program or shared[m
       library specified on the command line.[m
[m
   [1mSecurity[0m[m
       In the usual  case,  [1mldd[0m  invokes  the  standard  dynamic  linker  (see[m
       [1mld.so[0m(8))  with the [1mLD_TRACE_LOADED_OBJECTS[0m environment variable set to[m
       1, which causes the linker to display  the  library  dependencies.   Be[m
       aware,  however,  that  in some circumstances, some versions of [1mldd[0m may[m
       attempt to obtain the dependency information by directly executing  the[m
       program.  Thus, you should [4mnever[24m employ [1mldd[0m on an untrusted executable,[m
       since this may result in the execution  of  arbitrary  code.   A  safer[m
       alternative when dealing with untrusted executables is:[m
[m
           $ objdump -p /path/to/program | grep NEEDED[m
[7m Manual page ldd(1) line 1 (press h for help or q to quit)[27m[K[K[7m Manual page ldd(1) line 1 (press h for help or q to quit)[27m[K[K[m
[1mOPTIONS[0m[m
       [1m--version[0m[m
              Print the version number of [1mldd[0m.[m
[m
       [1m-v[0m [1m--verbose[0m[m
              Print all information, including, for example, symbol versioning[m
              information.[m
[m
       [1m-u[0m [1m--unused[0m[m
              Print unused direct dependencies.  (Since glibc 2.3.4.)[m
[m
[7m Manual page ldd(1) line 15 (press h for help or q to quit)[27m[K[K       [1m-d[0m [1m--data-relocs[0m[m
              Perform relocations and report any missing objects (ELF only).[m
[m
       [1m-r[0m [1m--function-relocs[0m[m
              Perform relocations for both data  objects  and  functions,  and[m
              report any missing objects or functions (ELF only).[m
[m
       [1m--help[0m Usage information.[m
[m
[1mNOTES[0m[m
       The  standard  version  of  [1mldd[0m  comes with glibc2.  Libc5 came with an[m
       older version, still present on some systems.  The long options are not[m
[7m Manual page ldd(1) line 27 (press h for help or q to quit)[27m[K[K[?1l>[?1049lbash-4.2$ la[Kdd simple
	linux-vdso.so.1 =>  (0x00007ffd8afc5000)
	libm.so.6 => /lib64/libm.so.6 (0x00007ff37c6a0000)
	libc.so.6 => /lib64/libc.so.6 (0x00007ff37c2d3000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff37c9a2000)
bash-4.2$ /[K./simple
Average is: 5.50
bash-4.2$ gdb
[?1034hGNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-114.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
(gdb) file simple
Reading symbols from /home/u1/yzg0032/simple...done.
(gdb) break a[Kmain
Breakpoint 1 at 0x400595: file simple.c, line 4.
(gdb) break sqrt
Breakpoint 2 at 0x400480
(gdb) info registers
The program has no registers now.
(gdb) r
Starting program: /home/u1/yzg0032/simple 

Breakpoint 1, main () at simple.c:4
4		int sample[10] = {1,4,9,16,25,36,49,64,81,100};
(gdb) n
5		double average = 0;
(gdb) s
6		int sum = 0;
(gdb) c
Continuing.

Breakpoint 2, __sqrt (x=1) at w_sqrt.c:27
27	  if (__builtin_expect (isless (x, 0.0), 0) && _LIB_VERSION != _IEEE_)
(gdb) qi[Kuit
A debugging session is active.

	Inferior 1 [process 2818] will be killed.

Quit anyway? (y or n) y
bash-4.2$ exit
exit

Script done on Wed 04 Sep 2019 07:54:47 PM CDT
